### ISSUE TITLE
Access token expire issue

### ISSUE THREAD

**Issue by nithinlogiticks** [Azure-Samples/active-directory-b2c-xamarin-native#119]
What should I do when access token got expired?is there any method in Microsoft.Identity.Client which updates the current access token?

**Comment by TiagoBrenck** [comment]
When you call `AcquireTokenSilent()`, MSAL will handle this for you automatically because it has the refresh token. However, if the refresh token is also expired, then you will get a `MsalUiRequiredException` which requires you to call `AcquireTokenInteractive()`.

More info in the [Readme](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native#about-the-code)

**Comment by jennyf19** [comment]
closing as answered -> @nithinlogiticks
