### ISSUE TITLE
AcquireTokenSilentAsync fails on User collection can't be null or empty

### ISSUE THREAD

**Issue by TomWalkerCodes** [Azure-Samples/active-directory-b2c-xamarin-native#16]
I'm not clear on the use case for using AcquireTokenSilentAsync.  It seems way different workflow from previous version.  Now you have to force the user to login into the app each time in order to populate the PublicClientApplication User collection.  Before I was able to store the token securely and not have to worry about keeping a user object around.  If the token was valid the user had access to the app.  There doesn't appear to be way to add a user to the PublicClientApplication User collection beyond having to call the AcquireTokenAsync.

**Comment by parakhj** [comment]
Could you provide code on how it worked "before"? Not sure what you are referring to

**Comment by Jeremywhiteley** [comment]
<img width="468" alt="screenshot 2017-06-26 10 18 13" src="https://user-images.githubusercontent.com/1545134/27551570-cadad93a-5a58-11e7-893e-b4fa48abeb1c.png">

**Comment by gsacavdm** [comment]
@TomWalkerCodes, re:

> Now you have to force the user to login into the app each time in order to populate the PublicClientApplication User collection.

You don't. AcquireTokenSilent will pickup the user from the user collection if they have previously signed in. If I recall correctly, the challenge is MSAL and the iOS emulator don't get along quite nicely yet so that persistence doesn't work there, but if you deploy to an actual iOS device, AcquireTokenSilent should pick up a previously signed in user.

**Comment by jennyf19** [comment]
@TomWalkerCodes @Jeremywhiteley Closing, as pretaining to an old version of MSAL. We have new cache mechanisms in v2+. If issue persists, please re-open. thank you!
