### ISSUE TITLE
Cancelling Sign up throws exception

### ISSUE THREAD

**Issue by tthiatma** [Azure-Samples/active-directory-b2c-xamarin-native#25]
Hello,

The application throws exception when I do below
Click sign in button -> Click sign up -> click cancel sign up
This exception found when testing on Android. 

Please check below screenshot
![2017-09-20_3-53-19](https://user-images.githubusercontent.com/4022533/30640319-54afca20-9db7-11e7-9e9e-ede105c56b7a.png)

**Comment by Ripper555** [comment]
This is by design. Write code to check for it:
`try`
`            {`
`               AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, `
`                   GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn)`, 
`                    App.UiParent);`

`                    UpdateUserInfo(ar);`
 `                   UpdateSignInState(true);`
 `            }`
`            catch(Exception ex)`
`            {`
`                // Checking the exception message `
`                // should ONLY be done for B2C`
`                // reset and not any other error.`
`                if (ex.Message.Contains("AADB2C90118"))`
`                   OnPasswordReset();`
`                // Alert if any exception excludig user cancelling sign-in dialog`
 `               else if (((ex as MsalException)?.ErrorCode != "authentication_canceled"))`
`                    await DisplayAlert($"Exception:", ex.ToString(), "Dismiss");`
`            }`

**Comment by tthiatma** [comment]
I see, thank you for the explanation (I'm pretty new to this). 
I am able to catch the exception in OnSignInSignOut
