### ISSUE TITLE
Question: What is MainPageRenderer good for?

### ISSUE THREAD

**Issue by daniel-kun** [Azure-Samples/active-directory-b2c-xamarin-native#31]
Lacking a better place to ask questions, I opened an issue here. I hope this is OK.

What is the MainPageRenderer class good for? It essentially does nothing, but store the active page in a member variable. Additionally, I don't see the class instantiated.

**Comment by gsacavdm** [comment]
At a high level, this is a key component of customizing the look-and-feel of your application. It doesn't do much in this sample because this is a simple Azure AD B2C sample. Check out more advance Xamarin docs & samples to see this guy in action, for example:

https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/contentpage/
