### ISSUE TITLE
Offline access doesn't work for basic login without an API

### ISSUE THREAD

**Issue by Ryan-Palmer** [Azure-Samples/active-directory-b2c-xamarin-native#44]
Hi there. I am using basically the same implementation in my Xamarin iOS native app as the Forms demo.

I am *not* trying to access a web api.I am just using AD B2C for sign in. I do not, therefore, get an Access Token back, which makes sense. I do get an ID token.

The problem I have is that when offline I would expect calling 'AcquireTokenSilentAsync' would return a success if we have previously signed in successfully, and are within within the signup policy expiration window.

What I find is that if I sign in, exit the app, turn off internet, relaunch and try to sign in again immediately, the request just fails and I get a HTTP exception.This means users always need to have internet to launch the app.

As far as I can tell, openId and offline_access are both now implicit scopes - adding them results in an error message saying so. However, I am forced to put in a dummy scope for the auth request - it has to be dummy as I have no api to add a scope for since it's a 'sign in only' client app. This feels like a weird design, unless I am missing something. You can no longer just put your Client (App) ID in to get ID token refresh as suggested elsewhere.

If I have internet, it all works fine and acquire silent succeeds.

Is it the case that without an Access token (for an api) I get no offline ability? The Expires property in the AuthentictionResult is default DateTime 1970 blah blah, which is supposed to be for the Access token which is null.

**Comment by RyanBuzzInteractive** [comment]
Ok, I just created a stub Web Api app and added its user_impersonation scope to my Web Client app and my Xamarin native mobile app. 

Now that I am accessing a real api, using a real scope, I get back an Access token, as you would expect. I also get an Expiry in the AuthenticationResult.

This has made the offline login work properly. 

I won't mark the issue as resolved though, as it seems the need to create a web api when all you want is simple login is not great, and I imagine someone else will have the same issue in future. It seems you used to be able to achieve what I want by passing your Client (App) Id as a scope, which is no longer possible since B2C started supporting Access tokens.

**Comment by Surfrat** [comment]
I am facing the same issue. Anyone found a workaround that does not require the creation of Web API?

**Comment by Surfrat** [comment]
@RyanBuzzInteractive Could I please email you a few questions as I am struggling with this last step. I have everything working across all three platforms except the offline storage. My email is surfrat77[[[[at]]]]gmail[[[dot]]]com.

Thanks.
