### ISSUE TITLE
Unable to use my own tenant

### ISSUE THREAD

**Issue by tthiatma** [Azure-Samples/active-directory-b2c-xamarin-native#70]
Hello,

When running the project with default setting. Everything works fine.

So I tried to create my own tenant and I got below error 
![image](https://user-images.githubusercontent.com/4022533/50261880-bc113700-03cb-11e9-863d-9b96c2c5e5c8.png)

Is there any detail steps on how to create tenant with screenshots for optional step 2 - 6 ?
I will create pull request to the documentation if someone can help me on creating the tenant.

Regards,
Tonny

**Comment by jennyf19** [comment]
@tthiatma Are you replacing the tenant, policies, client_id, scopes, authority (`{tenant}.b2clogin.com` instead of login.microsoftonline.com in the same) with the values in the sample and then getting the above error message? Do you have the redirectUri registered with your app as well in the portal?

**Comment by tthiatma** [comment]
@jennyf19  this is embarrassing, but I made a typo on my tenant url....
I am using login.microsoftonline.com and I got it to work with google sign in

**Comment by jennyf19** [comment]
@tthiatma Awesome! Can we close this issue? Thanks for the update.

**Comment by tthiatma** [comment]
I will give b2clogin.com a try. thank you for the info
