### ISSUE TITLE
iOS Simulator cannot_access_publisher_keychain

### ISSUE THREAD

**Issue by jimwallery** [Azure-Samples/active-directory-b2c-xamarin-native#94]
Entitlements.plist to Xamarin iOS cannot_access_publisher_keychain ErrorCode

Running the sample code for the UserDetailsClient sample I am receiving the above error when running the iPhoneSimulator.  The sample runs fine in Android and UWP. 

![cannot_access_publisher_keychain](https://user-images.githubusercontent.com/39068307/60545055-c350c000-9cdf-11e9-967f-5836697159cc.PNG)

**Comment by TiagoBrenck** [comment]
Hello @jimwallery, I had faced this issue and after investigating it, I found that the problem is related to the iOS provisioning profile. To solve it, you need to create a different provisioning profile (with a different name) because the Bundle Identifier needs to be unique.

### Creating a provisioning profile
The provisioning profile name used in this sample is `com.yourcompany.UserDetailsClient` (you can find it at `Info.plist` on **Bundle Identifier** field). Apple has a policy that these identifiers must be unique, so what you have to do is:
1. On your MAC, open XCode and create a new project
1. Open XCode preferences, navigate to **Account** tab and make sure you add your Apple Developer account
1. Close the preferences and on the navigation panel on the left, click on your project name. Then, under **General tab** check the option **Automatically manage signing**. Then select your team from the dropdown.
1. On the same screen, find the **Bundle Identifier** field, type a unique name ([check Apple s best practices for bundle identifier](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/AppID.html)) and press enter.
1. You will notice that XCode will automatically generate a profile for you.
1. Now, go back to Visual Studio, open `Info.plist` and change the Bundle Identifier value with the one you have just created
1. Right click on the iOS project, select *Properties* then navigate to *iOS Bundle Signing* on the left panel.
1. Check the option **Manual Provisioning**
1. On **Signing Identity** dropdown, select your Apple Developer account (it must be the same one that you used on XCode).
1. On **Provisioning Profile** dropdown, select **Automatic**.

This should solve the problem

**Comment by jimwallery** [comment]
I have tried the solution identified above and am running into the same error message.  So the solution suggested didn't seem to work.  Any other thoughts?

**Comment by TiagoBrenck** [comment]
@jimwallery on step 10, instead of selecting **Automatic**, do you see the profile that you created on XCode as one of the options?

**Comment by jimwallery** [comment]
Btw.  Your help on this is greatly appreciated!!!

I have gotten past the provisioning profile issue.  It was a matter of getting the Authentication Service constant for the IOSKeyChainGroup, the  iOSBundling Signing Provisioning Profile and the Entitlements.plist Enable Keychain Keychain Groups in alignment.  Also had to make an adjustment to my AppDelegate OpenURL method differing from the sample but it gets past the keychain issue encountered.

So now I get a message on the app iOS Simulator that appears below.  Any suggestions on managing this exception?

[cid:image001.png@01D53729.7116E3D0]

**Comment by TiagoBrenck** [comment]
@jimwallery the image with the exception didn't load. Could you please send it again?

**Comment by jimwallery** [comment]
Here is another try at sending the image.  Thank you for your help with this.

**Comment by TiagoBrenck** [comment]
@jimwallery the image is not being successfully attached. Could you please, just drag and drop the image using GitHub website instead of email? Thanks

**Comment by jimwallery** [comment]
ok will do.  apologies on the image.

Sent from my iPhone

On Jul 12, 2019, at 4:40 PM, Tiago Brenck <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimwallery<https://github.com/jimwallery> the image is not being successfully attached. Could you please, just drag and drop the image using GitHub website instead of email? Thanks

**Comment by jimwallery** [comment]
Attached is the image with the exception that I am encountering.
![MicrosoftIdentityClientiOSerror](https://user-images.githubusercontent.com/39068307/61235348-eecda480-a6fa-11e9-8bf6-668173c92591.jpg)

**Comment by TiagoBrenck** [comment]
@jimwallery, on **UserDetailsClient.iOS** project, open the file `Entitlements.plist` using Visual Studio. Then on the left menu, navigate to **Keychain**. Make sure that the option **Enable Keychain** is checked, and `com.com.2BG.CatchallRound3` is registered in the **Keychain Groups** box.

Another thing to check is:

1. Right click on  **UserDetailsClient.iOS** project and select Properties.
1. Navigate to **iOS Bundle Signing**
1. Type `Entitlements.plist` for **Custom Entitlements** textbox

**Comment by jimwallery** [comment]
With your help, I resolved the issue.

The entitlements required that I enter ‘com.com.2BG.CatchallRound3’.   I had mistakenly thought that the Provisioning Profile of : ‘com.2BG.CatchallRound3’ should be the same as the entitlements.plist keychain rather than requiring the extra ‘com.’    Thank you for your patience and in helping me to resolve this issue!

Just to confirm is the requirement of an extra ‘com.’ In the Entitlements.plist keychain a bug or something I am missing on my side?  No worries either way.

Thanks again!!

Jim

**Comment by jimwallery** [comment]
With your help, I resolved the issue.  

The entitlements required that I enter ‘com.com.2BG.CatchallRound3’.   I had mistakenly thought that the Provisioning Profile of : ‘com.2BG.CatchallRound3’ should be the same as the entitlements.plist keychain rather than requiring the extra ‘com.’    Thank you for your patience and in helping me to resolve this issue!

Just to confirm is the requirement of an extra ‘com.’ In the Entitlements.plist keychain a bug or something I am missing on my side?  No worries either way.

Thanks again!!

**Comment by TiagoBrenck** [comment]
@jimwallery I don't think there is a requirement for the 'com.'. If you go to `B2CConstants.cs` on **UserDetailsClient.Core** project, there is a const for `IOSKeyChainGroup`. This sample is using "com.microsoft.adalcache" but I assume you want to use your company`s Keychain, so you will have to update this const.

Apple has a suggestion for the names, recommending the developers to use an inverse domain pattern so it provides an easy to read, meanful but unique name. So in your case, if you want to use `com.2BG.CatchallRound3` for Keychain group name, you should add it to the **Entitlements.plist** and modify **B2CConstants.cs**
